# Generated by Django 3.1.3 on 2020-11-23 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RegDate', models.DateField(auto_now_add=True)),
                ('TotalFee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('St_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('St_name', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7, null=True)),
                ('Qualification', models.CharField(max_length=30)),
                ('Semester', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Subject_attempts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_code', models.CharField(max_length=10)),
                ('attempts', models.IntegerField(default=0)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=70)),
                ('Duration', models.IntegerField()),
                ('DateofExam', models.DateField()),
                ('Fee', models.FloatField()),
                ('Registration', models.ManyToManyField(to='main.Register')),
            ],
        ),
        migrations.AddField(
            model_name='register',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student'),
        ),
    ]
