# Generated by Django 3.1.3 on 2020-11-23 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='Registration',
        ),
        migrations.RemoveField(
            model_name='subject_attempts',
            name='Student',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Subject_attempts',
        ),
    ]
