# Generated by Django 3.1.3 on 2020-11-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201123_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Email',
        ),
        migrations.AlterField(
            model_name='register',
            name='TotalFee',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Qualification',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Duration',
            field=models.IntegerField(default=180),
        ),
    ]
