# Generated by Django 3.1.3 on 2020-11-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201124_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='Registration',
        ),
        migrations.AddField(
            model_name='register',
            name='Subjects',
            field=models.ManyToManyField(to='main.Subject'),
        ),
    ]
