# Generated by Django 3.1.3 on 2020-11-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201124_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_attempts',
            name='Passes',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
