# Generated by Django 3.1.3 on 2020-11-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_subject_attempts_passes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject_attempts',
            old_name='Passes',
            new_name='Passed',
        ),
    ]
