# Generated by Django 3.1.3 on 2020-11-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201124_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Semester',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='Sub_code',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
