# Generated by Django 3.1.3 on 2020-11-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201124_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Qualification',
        ),
        migrations.AddField(
            model_name='student',
            name='Department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('Mechanical', 'Mech'), ('IT', 'IT'), ('ECE', 'ECE')], default='CSE', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='Department',
            field=models.CharField(choices=[('CSE', 'CSE'), ('Mechanical', 'Mech'), ('IT', 'IT'), ('ECE', 'ECE')], default='CSE', max_length=30),
            preserve_default=False,
        ),
    ]
