# Generated by Django 3.1.3 on 2020-11-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201125_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Payed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subject_attempts',
            name='Passed',
            field=models.BooleanField(default=False),
        ),
    ]
