# Generated by Django 3.1.3 on 2020-12-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201201_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='Payed',
            new_name='Paid',
        ),
    ]
